version: '3.8'

services:
  # El "cerebro" (La API de ACE-Step)
  acestep-api:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: acestep_api
    ports:
      # Exponemos la API en el puerto 18001 hacia afuera
      - "18001:8001"
    volumes:
      - acestep_data:/root/.cache/huggingface 
    restart: unless-stopped

  # La "cara" (La interfaz Studio UI)
  acestep-studio-ui:
    image: nginx:alpine
    container_name: acestep_studio_ui
    ports:
      # Exponemos la web en el puerto 18080 hacia afuera
      - "18080:80"
    volumes:
      - ./ui/studio:/usr/share/nginx/html:ro
    depends_on:
      - acestep-api
    restart: unless-stopped

volumes:
  acestep_data:
